### ISSUE TITLE
Default username and password

### ISSUE THREAD

**Issue by tylergale** [foxmask/dj-diabetes#7]
Followed the Readme and have the application successfully running, but cannot find a default username and password to log into the application.  Is this missing from the Readme, or is there something that I missed?

**Comment by tylergale** [comment]
Upon further investigation, users need to be created before using the application.  After creating a user via manage.py, I was able to successfully log into the application. Apologies for my lack of understanding surrounding this issue!

**Comment by foxmask** [comment]
No problem :) 
I could say in the README the necessary step to do python manage.py createsupersuer
